version: "3.8"

services:
  dev-db:
    container_name: studapart-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: studapartDB
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    # volumes:
    #   - database_data:/var/lib/postgresql/data:rw
# volumes:
#   ###> doctrine/doctrine-bundle ###
#   database_data:
###< doctrine/doctrine-bundle ###

